# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli" do
  name "cli"
  desc "KeeperHub CLI -- manage workflows, executions, and Web3 automation"
  homepage "https://github.com/keeperhub/cli"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cli"
  bash_completion "completions/kh.bash"
  zsh_completion "completions/kh.zsh"
  fish_completion "completions/kh.fish"

  on_macos do
    on_intel do
      url "https://github.com/KeeperHub/cli/releases/download/v#{version}/kh_#{version}_darwin_amd64.tar.gz"
      sha256 "987b2bdb75267be15d4c3c53659562cd79087bf863d5657bfbbb8b305e975847"
    end
    on_arm do
      url "https://github.com/KeeperHub/cli/releases/download/v#{version}/kh_#{version}_darwin_arm64.tar.gz"
      sha256 "e26fbc4e83ff839952380ea84e5cf55020bbf0fbe956e966a7ee0ba7201e75ba"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/KeeperHub/cli/releases/download/v#{version}/kh_#{version}_linux_amd64.tar.gz"
      sha256 "1e13fa17da8464dad3ae3da2716c2b82c25a591e0b933a0ddb87209aa594f296"
    end
    on_arm do
      url "https://github.com/KeeperHub/cli/releases/download/v#{version}/kh_#{version}_linux_arm64.tar.gz"
      sha256 "dffdc81c88ffe3b3484cfe7b3cad1f340e6b1e908822b609e5fc21df19be9bc9"
    end
  end

  # No zap stanza required
end
