# This file was generated by GoReleaser. DO NOT EDIT.
cask "kh" do
  version "0.14.0"

  on_macos do
    on_intel do
      sha256 "497a7c9c9144b406ddb49cd6b3c941e56733e5dd6c768ebdf5d44d6aa9128c9a"
      url "https://github.com/KeeperHub/cli/releases/download/v#{version}/kh_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "df5c9d0e1dc87f6599bac9a9d89d921515986a33bba25a5d6bd1eaf56356fdbe"
      url "https://github.com/KeeperHub/cli/releases/download/v#{version}/kh_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cffb3d4d2e89a5922bb0a9427f078f54aca6fb3cd4307bf46807c1fc09280bd2"
      url "https://github.com/KeeperHub/cli/releases/download/v#{version}/kh_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3c8ae9abeefe08e07ab02cae5a55ac3b29fbaf61546177f49681f4d3bff20404"
      url "https://github.com/KeeperHub/cli/releases/download/v#{version}/kh_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kh"
  desc "KeeperHub CLI -- manage workflows, executions, and Web3 automation"
  homepage "https://github.com/keeperhub/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kh"
  bash_completion "completions/kh.bash"
  fish_completion "completions/kh.fish"
  zsh_completion "completions/kh.zsh"

  # No zap stanza required

end
