# This file was generated by GoReleaser. DO NOT EDIT.
cask "kh" do
  name "kh"
  desc "KeeperHub CLI -- manage workflows, executions, and Web3 automation"
  homepage "https://github.com/keeperhub/cli"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kh"
  bash_completion "completions/kh.bash"
  zsh_completion "completions/kh.zsh"
  fish_completion "completions/kh.fish"

  on_macos do
    on_intel do
      url "https://github.com/KeeperHub/cli/releases/download/v#{version}/kh_#{version}_darwin_amd64.tar.gz"
      sha256 "417e68c737c669e61fbe65670fc32043c170fb109ac0ce550b3e56b813220abf"
    end
    on_arm do
      url "https://github.com/KeeperHub/cli/releases/download/v#{version}/kh_#{version}_darwin_arm64.tar.gz"
      sha256 "fda090e3a33c3a4900215bdd3c68f22aacfc2de47c1fad1726ad78d05442250f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/KeeperHub/cli/releases/download/v#{version}/kh_#{version}_linux_amd64.tar.gz"
      sha256 "7a52019cad1f9ecde35af40bcdd5554991ede2db36f7d11114f3405f0c2b20a5"
    end
    on_arm do
      url "https://github.com/KeeperHub/cli/releases/download/v#{version}/kh_#{version}_linux_arm64.tar.gz"
      sha256 "ca13be9f3ff4c941fa7018459b832b138d716d71b768d83cfc9ca3f7b9280a55"
    end
  end

  # No zap stanza required
end
