# This file was generated by GoReleaser. DO NOT EDIT.
cask "kh" do
  name "kh"
  desc "KeeperHub CLI -- manage workflows, executions, and Web3 automation"
  homepage "https://github.com/keeperhub/cli"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kh"
  bash_completion "completions/kh.bash"
  zsh_completion "completions/kh.zsh"
  fish_completion "completions/kh.fish"

  on_macos do
    on_intel do
      url "https://github.com/KeeperHub/cli/releases/download/v#{version}/kh_#{version}_darwin_amd64.tar.gz"
      sha256 "88b081b1c8b46271d5147096cf993cd9995b64ed5bd8a12ceb9cc8ab351b84f8"
    end
    on_arm do
      url "https://github.com/KeeperHub/cli/releases/download/v#{version}/kh_#{version}_darwin_arm64.tar.gz"
      sha256 "d7b12ca4c5cfe7288ffc23cc3c5c007b0418201cabfa79b9f073f51dd49536ec"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/KeeperHub/cli/releases/download/v#{version}/kh_#{version}_linux_amd64.tar.gz"
      sha256 "9c002c938612b9e7bc0e02b4720c43f0091df16d4d43eb42c3e6cb2130c3c973"
    end
    on_arm do
      url "https://github.com/KeeperHub/cli/releases/download/v#{version}/kh_#{version}_linux_arm64.tar.gz"
      sha256 "bcdf54b0e5a915936695aacca3ea3d5d5adada95b5f34fc078a13812856e64cb"
    end
  end

  # No zap stanza required
end
